package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CallerWebServiceId generated by hbm2java
 */
@Embeddable
public class CallerWebServiceId implements java.io.Serializable {

	private long callerId;
	private long webServiceId;

	public CallerWebServiceId() {
	}

	public CallerWebServiceId(long callerId, long webServiceId) {
		this.callerId = callerId;
		this.webServiceId = webServiceId;
	}

	@Column(name = "caller_id", nullable = false)
	public long getCallerId() {
		return this.callerId;
	}

	public void setCallerId(long callerId) {
		this.callerId = callerId;
	}

	@Column(name = "web_service_id", nullable = false)
	public long getWebServiceId() {
		return this.webServiceId;
	}

	public void setWebServiceId(long webServiceId) {
		this.webServiceId = webServiceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CallerWebServiceId))
			return false;
		CallerWebServiceId castOther = (CallerWebServiceId) other;

		return (this.getCallerId() == castOther.getCallerId())
				&& (this.getWebServiceId() == castOther.getWebServiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCallerId();
		result = 37 * result + (int) this.getWebServiceId();
		return result;
	}

}
