package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CallerServer generated by hbm2java
 */
@Entity
@Table(name = "caller_server", catalog = "test_authentification_manager")
public class CallerServer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private CallerServerId id;
	private Caller caller;
	private Server server;

	public CallerServer() {
	}

	public CallerServer(CallerServerId id, Caller caller, Server server) {
		this.id = id;
		this.caller = caller;
		this.server = server;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "callerId", column = @Column(name = "caller_id", nullable = false)),
			@AttributeOverride(name = "serverId", column = @Column(name = "server_id", nullable = false)) })
	public CallerServerId getId() {
		return this.id;
	}

	public void setId(CallerServerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id", nullable = false, insertable = false, updatable = false)
	public Caller getCaller() {
		return this.caller;
	}

	public void setCaller(Caller caller) {
		this.caller = caller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "server_id", nullable = false, insertable = false, updatable = false)
	public Server getServer() {
		return this.server;
	}

	public void setServer(Server server) {
		this.server = server;
	}

}
