package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CallerServerId generated by hbm2java
 */
@Embeddable
public class CallerServerId implements java.io.Serializable {

	private long callerId;
	private long serverId;

	public CallerServerId() {
	}

	public CallerServerId(long callerId, long serverId) {
		this.callerId = callerId;
		this.serverId = serverId;
	}

	@Column(name = "caller_id", nullable = false)
	public long getCallerId() {
		return this.callerId;
	}

	public void setCallerId(long callerId) {
		this.callerId = callerId;
	}

	@Column(name = "server_id", nullable = false)
	public long getServerId() {
		return this.serverId;
	}

	public void setServerId(long serverId) {
		this.serverId = serverId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CallerServerId))
			return false;
		CallerServerId castOther = (CallerServerId) other;

		return (this.getCallerId() == castOther.getCallerId()) && (this.getServerId() == castOther.getServerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCallerId();
		result = 37 * result + (int) this.getServerId();
		return result;
	}

}
