package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CallerWebService generated by hbm2java
 */
@Entity
@Table(name = "caller_web_service", catalog = "test_authentification_manager")
public class CallerWebService implements java.io.Serializable {

	private CallerWebServiceId id;
	private Caller caller;
	private WebService webService;

	public CallerWebService() {
	}

	public CallerWebService(CallerWebServiceId id, Caller caller, WebService webService) {
		this.id = id;
		this.caller = caller;
		this.webService = webService;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "callerId", column = @Column(name = "caller_id", nullable = false)),
			@AttributeOverride(name = "webServiceId", column = @Column(name = "web_service_id", nullable = false)) })
	public CallerWebServiceId getId() {
		return this.id;
	}

	public void setId(CallerWebServiceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id", nullable = false, insertable = false, updatable = false)
	public Caller getCaller() {
		return this.caller;
	}

	public void setCaller(Caller caller) {
		this.caller = caller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "web_service_id", nullable = false, insertable = false, updatable = false)
	public WebService getWebService() {
		return this.webService;
	}

	public void setWebService(WebService webService) {
		this.webService = webService;
	}

}
