package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scope generated by hbm2java
 */
@Entity
@Table(name = "scope", catalog = "test_authentification_manager", uniqueConstraints = @UniqueConstraint(columnNames = "label"))
public class Scope implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long id;
	private String label;
	private Set<Caller> callers = new HashSet<Caller>(0);

	public Scope() {
	}

	public Scope(long id, String label) {
		this.id = id;
		this.label = label;
	}

	public Scope(long id, String label, Set<Caller> callers) {
		this.id = id;
		this.label = label;
		this.callers = callers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "label", unique = true, nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scope")
	public Set<Caller> getCallers() {
		return this.callers;
	}

	public void setCallers(Set<Caller> callers) {
		this.callers = callers;
	}

}
