package tn.wevioo.authentication.entities;
// Generated 13 avr. 2017 17:13:26 by Hibernate Tools 5.1.2.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebService generated by hbm2java
 */
@Entity
@Table(name = "web_service", catalog = "test_authentification_manager")
public class WebService implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Users usersByCreatorId;
	private Users usersByModifierId;
	private Date created;
	private String description;
	private Date modified;
	private String name;
	private Set<CallerWebService> callerWebServices = new HashSet<CallerWebService>(0);

	public WebService() {
	}

	public WebService(Users usersByCreatorId, Date created, String name) {
		this.usersByCreatorId = usersByCreatorId;
		this.created = created;
		this.name = name;
	}

	public WebService(Users usersByCreatorId, Users usersByModifierId, Date created, String description, Date modified,
			String name, Set<CallerWebService> callerWebServices) {
		this.usersByCreatorId = usersByCreatorId;
		this.usersByModifierId = usersByModifierId;
		this.created = created;
		this.description = description;
		this.modified = modified;
		this.name = name;
		this.callerWebServices = callerWebServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator_id", nullable = false)
	public Users getUsersByCreatorId() {
		return this.usersByCreatorId;
	}

	public void setUsersByCreatorId(Users usersByCreatorId) {
		this.usersByCreatorId = usersByCreatorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modifier_id")
	public Users getUsersByModifierId() {
		return this.usersByModifierId;
	}

	public void setUsersByModifierId(Users usersByModifierId) {
		this.usersByModifierId = usersByModifierId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webService")
	public Set<CallerWebService> getCallerWebServices() {
		return this.callerWebServices;
	}

	public void setCallerWebServices(Set<CallerWebService> callerWebServices) {
		this.callerWebServices = callerWebServices;
	}

}
