package tn.wevioo.packager.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackagerInstanceActionReportTemplate generated by hbm2java
 */
@Entity
@Table(name = "packager_instance_action_report_template", catalog = "nn_packager_management_recette")
public class PackagerInstanceActionReportTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String singleLineTemplate;
	private Date lastUpdate;

	public PackagerInstanceActionReportTemplate() {
	}

	public PackagerInstanceActionReportTemplate(String id, Date lastUpdate) {
		this.id = id;
		this.lastUpdate = lastUpdate;
	}

	public PackagerInstanceActionReportTemplate(String id, String singleLineTemplate, Date lastUpdate) {
		this.id = id;
		this.singleLineTemplate = singleLineTemplate;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "single_line_template", length = 1024)
	public String getSingleLineTemplate() {
		return this.singleLineTemplate;
	}

	public void setSingleLineTemplate(String singleLineTemplate) {
		this.singleLineTemplate = singleLineTemplate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
