package tn.wevioo.packager.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scenario generated by hbm2java
 */
@Entity
@Table(name = "scenario", catalog = "nn_packager_management_recette", uniqueConstraints = @UniqueConstraint(columnNames = "reference"))
public class Scenario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String reference;
	private Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations = new HashSet<DeliveryTemplateConfiguration>(
			0);

	public Scenario() {
	}

	public Scenario(String reference) {
		this.reference = reference;
	}

	public Scenario(String reference, Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations) {
		this.reference = reference;
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "reference", unique = true, nullable = false)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenario")
	public Set<DeliveryTemplateConfiguration> getDeliveryTemplateConfigurations() {
		return this.deliveryTemplateConfigurations;
	}

	public void setDeliveryTemplateConfigurations(Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations) {
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
	}

}
