package tn.wevioo.packager.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPackagerDomainForCubeId generated by hbm2java
 */
@Embeddable
public class VPackagerDomainForCubeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String retailerPackagerId;
	private String providerProductId;
	private String domainName;

	public VPackagerDomainForCubeId() {
	}

	public VPackagerDomainForCubeId(String retailerPackagerId, String providerProductId) {
		this.retailerPackagerId = retailerPackagerId;
		this.providerProductId = providerProductId;
	}

	public VPackagerDomainForCubeId(String retailerPackagerId, String providerProductId, String domainName) {
		this.retailerPackagerId = retailerPackagerId;
		this.providerProductId = providerProductId;
		this.domainName = domainName;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "provider_product_id", nullable = false)
	public String getProviderProductId() {
		return this.providerProductId;
	}

	public void setProviderProductId(String providerProductId) {
		this.providerProductId = providerProductId;
	}

	@Column(name = "domain_name")
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPackagerDomainForCubeId))
			return false;
		VPackagerDomainForCubeId castOther = (VPackagerDomainForCubeId) other;

		return ((this.getRetailerPackagerId() == castOther.getRetailerPackagerId())
				|| (this.getRetailerPackagerId() != null && castOther.getRetailerPackagerId() != null
						&& this.getRetailerPackagerId().equals(castOther.getRetailerPackagerId())))
				&& ((this.getProviderProductId() == castOther.getProviderProductId())
						|| (this.getProviderProductId() != null && castOther.getProviderProductId() != null
								&& this.getProviderProductId().equals(castOther.getProviderProductId())))
				&& ((this.getDomainName() == castOther.getDomainName())
						|| (this.getDomainName() != null && castOther.getDomainName() != null
								&& this.getDomainName().equals(castOther.getDomainName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRetailerPackagerId() == null ? 0 : this.getRetailerPackagerId().hashCode());
		result = 37 * result + (getProviderProductId() == null ? 0 : this.getProviderProductId().hashCode());
		result = 37 * result + (getDomainName() == null ? 0 : this.getDomainName().hashCode());
		return result;
	}

}
