//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 09:50:38 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nordnet.com/manualDriver", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tn.wevioo.properties;
