//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 09:50:38 AM WAT 
//


package tn.wevioo.properties;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TCivility.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TCivility">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="M."/>
 *     &lt;enumeration value="Mlle"/>
 *     &lt;enumeration value="Mme"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TCivility", namespace = "http://www.nordnet.com/generic/types")
@XmlEnum
public enum TCivility {

    @XmlEnumValue("M.")
    M("M."),
    @XmlEnumValue("Mlle")
    MLLE("Mlle"),
    @XmlEnumValue("Mme")
    MME("Mme");
    private final String value;

    TCivility(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TCivility fromValue(String v) {
        for (TCivility c: TCivility.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
