package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AuthorizedIpAddress generated by hbm2java
 */
@Entity
@Table(name = "authorized_ip_address", catalog = "nn_packager_management_recette", uniqueConstraints = @UniqueConstraint(columnNames = {
		"address", "id_web_service_user" }))
public class AuthorizedIpAddress implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private WebServiceUser webServiceUser;
	private String address;

	public AuthorizedIpAddress() {
	}

	public AuthorizedIpAddress(WebServiceUser webServiceUser, String address) {
		this.webServiceUser = webServiceUser;
		this.address = address;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_web_service_user", nullable = false)
	public WebServiceUser getWebServiceUser() {
		return this.webServiceUser;
	}

	public void setWebServiceUser(WebServiceUser webServiceUser) {
		this.webServiceUser = webServiceUser;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
