package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeliveryTemplate generated by hbm2java
 */
@Entity
@Table(name = "delivery_template", catalog = "nn_packager_management_recette", uniqueConstraints = @UniqueConstraint(columnNames = "template_name"))
public class DeliveryTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8372414990566199947L;
	private Integer id;
	private String templateName;
	private Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations = new HashSet<DeliveryTemplateConfiguration>(
			0);

	public DeliveryTemplate() {
	}

	public DeliveryTemplate(String templateName) {
		this.templateName = templateName;
	}

	public DeliveryTemplate(String templateName, Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations) {
		this.templateName = templateName;
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "template_name", unique = true, nullable = false)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryTemplate")
	public Set<DeliveryTemplateConfiguration> getDeliveryTemplateConfigurations() {
		return this.deliveryTemplateConfigurations;
	}

	public void setDeliveryTemplateConfigurations(Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations) {
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
	}

}
