package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeliveryTemplateConfiguration generated by hbm2java
 */
@Entity
@Table(name = "delivery_template_configuration", catalog = "nn_packager_management_recette")
public class DeliveryTemplateConfiguration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private DeliveryTemplate deliveryTemplate;
	private PackagerModel packagerModel;
	private Scenario scenario;
	private boolean defaultTemplate;

	public DeliveryTemplateConfiguration() {
	}

	public DeliveryTemplateConfiguration(DeliveryTemplate deliveryTemplate, PackagerModel packagerModel,
			Scenario scenario, boolean defaultTemplate) {
		this.deliveryTemplate = deliveryTemplate;
		this.packagerModel = packagerModel;
		this.scenario = scenario;
		this.defaultTemplate = defaultTemplate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_delivery_template", nullable = false)
	public DeliveryTemplate getDeliveryTemplate() {
		return this.deliveryTemplate;
	}

	public void setDeliveryTemplate(DeliveryTemplate deliveryTemplate) {
		this.deliveryTemplate = deliveryTemplate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_model", nullable = false)
	public PackagerModel getPackagerModel() {
		return this.packagerModel;
	}

	public void setPackagerModel(PackagerModel packagerModel) {
		this.packagerModel = packagerModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_scenario", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Column(name = "default_template", nullable = false)
	public boolean isDefaultTemplate() {
		return this.defaultTemplate;
	}

	public void setDefaultTemplate(boolean defaultTemplate) {
		this.defaultTemplate = defaultTemplate;
	}

}
