package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FailedShippingDemand generated by hbm2java
 */
@Entity
@Table(name = "failed_shipping_demand", catalog = "nn_packager_management_recette")
public class FailedShippingDemand implements java.io.Serializable {

	private Integer id;
	private PackagerInstance packagerInstance;
	private String shippingXml;
	private Date creationDate;
	private Date lastUpdate;
	private Date lastAttempDate;

	public FailedShippingDemand() {
	}

	public FailedShippingDemand(PackagerInstance packagerInstance, String shippingXml, Date creationDate,
			Date lastUpdate, Date lastAttempDate) {
		this.packagerInstance = packagerInstance;
		this.shippingXml = shippingXml;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.lastAttempDate = lastAttempDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_instance")
	public PackagerInstance getPackagerInstance() {
		return this.packagerInstance;
	}

	public void setPackagerInstance(PackagerInstance packagerInstance) {
		this.packagerInstance = packagerInstance;
	}

	@Column(name = "shipping_xml", length = 65535)
	public String getShippingXml() {
		return this.shippingXml;
	}

	public void setShippingXml(String shippingXml) {
		this.shippingXml = shippingXml;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creation_date", length = 10)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_update", length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_attemp_date", length = 19)
	public Date getLastAttempDate() {
		return this.lastAttempDate;
	}

	public void setLastAttempDate(Date lastAttempDate) {
		this.lastAttempDate = lastAttempDate;
	}

}
