package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PackagerModelPossibleTransformations generated by hbm2java
 */
@Entity
@Table(name = "packager_model_possible_transformations", catalog = "nn_packager_management_recette", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_packager_model_from", "id_packager_model_to" }))
public class PackagerModelPossibleTransformations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PackagerModelPossibleTransformationsId id;
	private PackagerModel packagerModelByIdPackagerModelTo;
	private PackagerModel packagerModelByIdPackagerModelFrom;

	public PackagerModelPossibleTransformations() {
	}

	public PackagerModelPossibleTransformations(PackagerModelPossibleTransformationsId id,
			PackagerModel packagerModelByIdPackagerModelTo, PackagerModel packagerModelByIdPackagerModelFrom) {
		this.id = id;
		this.packagerModelByIdPackagerModelTo = packagerModelByIdPackagerModelTo;
		this.packagerModelByIdPackagerModelFrom = packagerModelByIdPackagerModelFrom;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPackagerModelFrom", column = @Column(name = "id_packager_model_from", nullable = false)),
			@AttributeOverride(name = "idPackagerModelTo", column = @Column(name = "id_packager_model_to", nullable = false)) })
	public PackagerModelPossibleTransformationsId getId() {
		return this.id;
	}

	public void setId(PackagerModelPossibleTransformationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_model_to", nullable = false, insertable = false, updatable = false)
	public PackagerModel getPackagerModelByIdPackagerModelTo() {
		return this.packagerModelByIdPackagerModelTo;
	}

	public void setPackagerModelByIdPackagerModelTo(PackagerModel packagerModelByIdPackagerModelTo) {
		this.packagerModelByIdPackagerModelTo = packagerModelByIdPackagerModelTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_model_from", nullable = false, insertable = false, updatable = false)
	public PackagerModel getPackagerModelByIdPackagerModelFrom() {
		return this.packagerModelByIdPackagerModelFrom;
	}

	public void setPackagerModelByIdPackagerModelFrom(PackagerModel packagerModelByIdPackagerModelFrom) {
		this.packagerModelByIdPackagerModelFrom = packagerModelByIdPackagerModelFrom;
	}

}
