package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackagerActionPackagerHeaderSource generated by hbm2java
 */
@Entity
@Table(name = "packager_action_packager_header_source", catalog = "nn_packager_management_recette")
public class PackagerActionPackagerHeaderSource implements java.io.Serializable {

	private Integer id;
	private PackagerActionHistory packagerActionHistory;
	private Retailer retailer;
	private String retailerPackagerId;
	private String packagerModelKey;
	private Date lastUpdate;

	public PackagerActionPackagerHeaderSource() {
	}

	public PackagerActionPackagerHeaderSource(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public PackagerActionPackagerHeaderSource(PackagerActionHistory packagerActionHistory, Retailer retailer,
			String retailerPackagerId, String packagerModelKey, Date lastUpdate) {
		this.packagerActionHistory = packagerActionHistory;
		this.retailer = retailer;
		this.retailerPackagerId = retailerPackagerId;
		this.packagerModelKey = packagerModelKey;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_action_history")
	public PackagerActionHistory getPackagerActionHistory() {
		return this.packagerActionHistory;
	}

	public void setPackagerActionHistory(PackagerActionHistory packagerActionHistory) {
		this.packagerActionHistory = packagerActionHistory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_retailer")
	public Retailer getRetailer() {
		return this.retailer;
	}

	public void setRetailer(Retailer retailer) {
		this.retailer = retailer;
	}

	@Column(name = "retailer_packager_id")
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "packager_model_key")
	public String getPackagerModelKey() {
		return this.packagerModelKey;
	}

	public void setPackagerModelKey(String packagerModelKey) {
		this.packagerModelKey = packagerModelKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
