package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PackagerModelProductModel generated by hbm2java
 */
@Entity
@Table(name = "packager_model_product_model", catalog = "nn_packager_management_recette")
public class PackagerModelProductModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private PackagerModel packagerModel;
	private ProductModel productModel;
	private int minimumInstances;
	private int maximumInstances;
	private Set<ProductModelShippableItemConfiguration> productModelShippableItemConfigurations = new HashSet<ProductModelShippableItemConfiguration>(
			0);

	public PackagerModelProductModel() {
	}

	public PackagerModelProductModel(PackagerModel packagerModel, ProductModel productModel, int minimumInstances,
			int maximumInstances) {
		this.packagerModel = packagerModel;
		this.productModel = productModel;
		this.minimumInstances = minimumInstances;
		this.maximumInstances = maximumInstances;
	}

	public PackagerModelProductModel(PackagerModel packagerModel, ProductModel productModel, int minimumInstances,
			int maximumInstances, Set<ProductModelShippableItemConfiguration> productModelShippableItemConfigurations) {
		this.packagerModel = packagerModel;
		this.productModel = productModel;
		this.minimumInstances = minimumInstances;
		this.maximumInstances = maximumInstances;
		this.productModelShippableItemConfigurations = productModelShippableItemConfigurations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_model", nullable = false)
	public PackagerModel getPackagerModel() {
		return this.packagerModel;
	}

	public void setPackagerModel(PackagerModel packagerModel) {
		this.packagerModel = packagerModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product_model", nullable = false)
	public ProductModel getProductModel() {
		return this.productModel;
	}

	public void setProductModel(ProductModel productModel) {
		this.productModel = productModel;
	}

	@Column(name = "minimumInstances", nullable = false)
	public int getMinimumInstances() {
		return this.minimumInstances;
	}

	public void setMinimumInstances(int minimumInstances) {
		this.minimumInstances = minimumInstances;
	}

	@Column(name = "maximumInstances", nullable = false)
	public int getMaximumInstances() {
		return this.maximumInstances;
	}

	public void setMaximumInstances(int maximumInstances) {
		this.maximumInstances = maximumInstances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModelProductModel")
	public Set<ProductModelShippableItemConfiguration> getProductModelShippableItemConfigurations() {
		return this.productModelShippableItemConfigurations;
	}

	public void setProductModelShippableItemConfigurations(
			Set<ProductModelShippableItemConfiguration> productModelShippableItemConfigurations) {
		this.productModelShippableItemConfigurations = productModelShippableItemConfigurations;
	}

}
