package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackagerInstance generated by hbm2java
 */
@Entity
@Table(name = "packager_instance", catalog = "nn_packager_management_recette_new")
public class PackagerInstance implements java.io.Serializable {

	private Integer idPackagerInstance;
	private PackagerModel packagerModel;
	private Retailer retailer;
	private String retailerPackagerId;
	private Date creationDate;
	private Date lastUpdate;
	private String toto;
	private Set<ShippingDemand> shippingDemands = new HashSet<ShippingDemand>(0);
	private Set<FailedShippingDemand> failedShippingDemands = new HashSet<FailedShippingDemand>(0);
	private Set<PackagerInstanceProductInstance> packagerInstanceProductInstances = new HashSet<PackagerInstanceProductInstance>(
			0);

	public PackagerInstance() {
	}

	public PackagerInstance(PackagerModel packagerModel, Retailer retailer, String retailerPackagerId,
			Date creationDate, Date lastUpdate) {
		this.packagerModel = packagerModel;
		this.retailer = retailer;
		this.retailerPackagerId = retailerPackagerId;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
	}

	public PackagerInstance(PackagerModel packagerModel, Retailer retailer, String retailerPackagerId,
			Date creationDate, Date lastUpdate, String toto, Set<ShippingDemand> shippingDemands,
			Set<FailedShippingDemand> failedShippingDemands,
			Set<PackagerInstanceProductInstance> packagerInstanceProductInstances) {
		this.packagerModel = packagerModel;
		this.retailer = retailer;
		this.retailerPackagerId = retailerPackagerId;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.toto = toto;
		this.shippingDemands = shippingDemands;
		this.failedShippingDemands = failedShippingDemands;
		this.packagerInstanceProductInstances = packagerInstanceProductInstances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_packager_instance", unique = true, nullable = false)
	public Integer getIdPackagerInstance() {
		return this.idPackagerInstance;
	}

	public void setIdPackagerInstance(Integer idPackagerInstance) {
		this.idPackagerInstance = idPackagerInstance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_model", nullable = false)
	public PackagerModel getPackagerModel() {
		return this.packagerModel;
	}

	public void setPackagerModel(PackagerModel packagerModel) {
		this.packagerModel = packagerModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_retailer", nullable = false)
	public Retailer getRetailer() {
		return this.retailer;
	}

	public void setRetailer(Retailer retailer) {
		this.retailer = retailer;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "toto")
	public String getToto() {
		return this.toto;
	}

	public void setToto(String toto) {
		this.toto = toto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerInstance")
	public Set<ShippingDemand> getShippingDemands() {
		return this.shippingDemands;
	}

	public void setShippingDemands(Set<ShippingDemand> shippingDemands) {
		this.shippingDemands = shippingDemands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerInstance")
	public Set<FailedShippingDemand> getFailedShippingDemands() {
		return this.failedShippingDemands;
	}

	public void setFailedShippingDemands(Set<FailedShippingDemand> failedShippingDemands) {
		this.failedShippingDemands = failedShippingDemands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerInstance")
	public Set<PackagerInstanceProductInstance> getPackagerInstanceProductInstances() {
		return this.packagerInstanceProductInstances;
	}

	public void setPackagerInstanceProductInstances(
			Set<PackagerInstanceProductInstance> packagerInstanceProductInstances) {
		this.packagerInstanceProductInstances = packagerInstanceProductInstances;
	}

}
