package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackagerModel generated by hbm2java
 */
@Entity
@Table(name = "packager_model", catalog = "nn_packager_management_recette")
public class PackagerModel implements java.io.Serializable {

	private Integer idPackagerModel;
	private String retailerKey;
	private String oldRetailerKey;
	private Date creationDate;
	private Date lastUpdate;
	private boolean multithreadedActions;
	private Set<Retailer> retailers = new HashSet<Retailer>(0);
	private Set<PackagerInstance> packagerInstances = new HashSet<PackagerInstance>(0);
	private Set<PackagerModelShippableItemConfiguration> packagerModelShippableItemConfigurations = new HashSet<PackagerModelShippableItemConfiguration>(
			0);
	private Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations = new HashSet<DeliveryTemplateConfiguration>(
			0);
	private Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelTo = new HashSet<PackagerModelPossibleTransformations>(
			0);
	private Set<PackagerModelProductModel> packagerModelProductModels = new HashSet<PackagerModelProductModel>(0);
	private Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelFrom = new HashSet<PackagerModelPossibleTransformations>(
			0);

	public PackagerModel() {
	}

	public PackagerModel(String oldRetailerKey, Date creationDate, Date lastUpdate, boolean multithreadedActions) {
		this.oldRetailerKey = oldRetailerKey;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.multithreadedActions = multithreadedActions;
	}

	public PackagerModel(String retailerKey, String oldRetailerKey, Date creationDate, Date lastUpdate,
			boolean multithreadedActions, Set<Retailer> retailers, Set<PackagerInstance> packagerInstances,
			Set<PackagerModelShippableItemConfiguration> packagerModelShippableItemConfigurations,
			Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations,
			Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelTo,
			Set<PackagerModelProductModel> packagerModelProductModels,
			Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelFrom) {
		this.retailerKey = retailerKey;
		this.oldRetailerKey = oldRetailerKey;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.multithreadedActions = multithreadedActions;
		this.retailers = retailers;
		this.packagerInstances = packagerInstances;
		this.packagerModelShippableItemConfigurations = packagerModelShippableItemConfigurations;
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
		this.packagerModelPossibleTransformationsesForIdPackagerModelTo = packagerModelPossibleTransformationsesForIdPackagerModelTo;
		this.packagerModelProductModels = packagerModelProductModels;
		this.packagerModelPossibleTransformationsesForIdPackagerModelFrom = packagerModelPossibleTransformationsesForIdPackagerModelFrom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_packager_model", unique = true, nullable = false)
	public Integer getIdPackagerModel() {
		return this.idPackagerModel;
	}

	public void setIdPackagerModel(Integer idPackagerModel) {
		this.idPackagerModel = idPackagerModel;
	}

	@Column(name = "retailer_key")
	public String getRetailerKey() {
		return this.retailerKey;
	}

	public void setRetailerKey(String retailerKey) {
		this.retailerKey = retailerKey;
	}

	@Column(name = "old_retailer_key", nullable = false)
	public String getOldRetailerKey() {
		return this.oldRetailerKey;
	}

	public void setOldRetailerKey(String oldRetailerKey) {
		this.oldRetailerKey = oldRetailerKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "multithreaded_actions", nullable = false)
	public boolean isMultithreadedActions() {
		return this.multithreadedActions;
	}

	public void setMultithreadedActions(boolean multithreadedActions) {
		this.multithreadedActions = multithreadedActions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "packagerModels")
	public Set<Retailer> getRetailers() {
		return this.retailers;
	}

	public void setRetailers(Set<Retailer> retailers) {
		this.retailers = retailers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModel")
	public Set<PackagerInstance> getPackagerInstances() {
		return this.packagerInstances;
	}

	public void setPackagerInstances(Set<PackagerInstance> packagerInstances) {
		this.packagerInstances = packagerInstances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModel")
	public Set<PackagerModelShippableItemConfiguration> getPackagerModelShippableItemConfigurations() {
		return this.packagerModelShippableItemConfigurations;
	}

	public void setPackagerModelShippableItemConfigurations(
			Set<PackagerModelShippableItemConfiguration> packagerModelShippableItemConfigurations) {
		this.packagerModelShippableItemConfigurations = packagerModelShippableItemConfigurations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModel")
	public Set<DeliveryTemplateConfiguration> getDeliveryTemplateConfigurations() {
		return this.deliveryTemplateConfigurations;
	}

	public void setDeliveryTemplateConfigurations(Set<DeliveryTemplateConfiguration> deliveryTemplateConfigurations) {
		this.deliveryTemplateConfigurations = deliveryTemplateConfigurations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModelByIdPackagerModelTo")
	public Set<PackagerModelPossibleTransformations> getPackagerModelPossibleTransformationsesForIdPackagerModelTo() {
		return this.packagerModelPossibleTransformationsesForIdPackagerModelTo;
	}

	public void setPackagerModelPossibleTransformationsesForIdPackagerModelTo(
			Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelTo) {
		this.packagerModelPossibleTransformationsesForIdPackagerModelTo = packagerModelPossibleTransformationsesForIdPackagerModelTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModel")
	public Set<PackagerModelProductModel> getPackagerModelProductModels() {
		return this.packagerModelProductModels;
	}

	public void setPackagerModelProductModels(Set<PackagerModelProductModel> packagerModelProductModels) {
		this.packagerModelProductModels = packagerModelProductModels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagerModelByIdPackagerModelFrom")
	public Set<PackagerModelPossibleTransformations> getPackagerModelPossibleTransformationsesForIdPackagerModelFrom() {
		return this.packagerModelPossibleTransformationsesForIdPackagerModelFrom;
	}

	public void setPackagerModelPossibleTransformationsesForIdPackagerModelFrom(
			Set<PackagerModelPossibleTransformations> packagerModelPossibleTransformationsesForIdPackagerModelFrom) {
		this.packagerModelPossibleTransformationsesForIdPackagerModelFrom = packagerModelPossibleTransformationsesForIdPackagerModelFrom;
	}

}
