package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductModel generated by hbm2java
 */
@Entity
@Table(name = "product_model", catalog = "nn_packager_management_recette")
public class ProductModel implements java.io.Serializable {

	private Integer idProductModel;
	private String retailerKey;
	private String oldRetailerKey;
	private Date creationDate;
	private Date lastUpdate;
	private String productDriverFactoryBeanName;
	private String defaultTemplateUrlV2;
	private String defaultConfigurationUri;
	private Set<PackagerModelProductModel> packagerModelProductModels = new HashSet<PackagerModelProductModel>(0);
	private Set<ProductInstance> productInstances = new HashSet<ProductInstance>(0);

	public ProductModel() {
	}

	public ProductModel(String oldRetailerKey, Date creationDate, Date lastUpdate,
			String productDriverFactoryBeanName) {
		this.oldRetailerKey = oldRetailerKey;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.productDriverFactoryBeanName = productDriverFactoryBeanName;
	}

	public ProductModel(String retailerKey, String oldRetailerKey, Date creationDate, Date lastUpdate,
			String productDriverFactoryBeanName, String defaultTemplateUrlV2, String defaultConfigurationUri,
			Set<PackagerModelProductModel> packagerModelProductModels, Set<ProductInstance> productInstances) {
		this.retailerKey = retailerKey;
		this.oldRetailerKey = oldRetailerKey;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.productDriverFactoryBeanName = productDriverFactoryBeanName;
		this.defaultTemplateUrlV2 = defaultTemplateUrlV2;
		this.defaultConfigurationUri = defaultConfigurationUri;
		this.packagerModelProductModels = packagerModelProductModels;
		this.productInstances = productInstances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_product_model", unique = true, nullable = false)
	public Integer getIdProductModel() {
		return this.idProductModel;
	}

	public void setIdProductModel(Integer idProductModel) {
		this.idProductModel = idProductModel;
	}

	@Column(name = "retailer_key")
	public String getRetailerKey() {
		return this.retailerKey;
	}

	public void setRetailerKey(String retailerKey) {
		this.retailerKey = retailerKey;
	}

	@Column(name = "old_retailer_key", nullable = false)
	public String getOldRetailerKey() {
		return this.oldRetailerKey;
	}

	public void setOldRetailerKey(String oldRetailerKey) {
		this.oldRetailerKey = oldRetailerKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "product_driver_factory_bean_name", nullable = false)
	public String getProductDriverFactoryBeanName() {
		return this.productDriverFactoryBeanName;
	}

	public void setProductDriverFactoryBeanName(String productDriverFactoryBeanName) {
		this.productDriverFactoryBeanName = productDriverFactoryBeanName;
	}

	@Column(name = "default_template_url_v2", length = 512)
	public String getDefaultTemplateUrlV2() {
		return this.defaultTemplateUrlV2;
	}

	public void setDefaultTemplateUrlV2(String defaultTemplateUrlV2) {
		this.defaultTemplateUrlV2 = defaultTemplateUrlV2;
	}

	@Column(name = "default_configuration_uri", length = 512)
	public String getDefaultConfigurationUri() {
		return this.defaultConfigurationUri;
	}

	public void setDefaultConfigurationUri(String defaultConfigurationUri) {
		this.defaultConfigurationUri = defaultConfigurationUri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productModel")
	public Set<PackagerModelProductModel> getPackagerModelProductModels() {
		return this.packagerModelProductModels;
	}

	public void setPackagerModelProductModels(Set<PackagerModelProductModel> packagerModelProductModels) {
		this.packagerModelProductModels = packagerModelProductModels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productModel")
	public Set<ProductInstance> getProductInstances() {
		return this.productInstances;
	}

	public void setProductInstances(Set<ProductInstance> productInstances) {
		this.productInstances = productInstances;
	}

}
