package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingDemand generated by hbm2java
 */
@Entity
@Table(name = "shipping_demand", catalog = "nn_packager_management_recette")
public class ShippingDemand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer packId;
	private PackagerInstance packagerInstance;
	private Integer id;
	private Date creationDate;
	private Date lastUpdate;
	private boolean declined;
	private Set<ProductInstance> productInstances = new HashSet<ProductInstance>(0);

	public ShippingDemand() {
	}

	public ShippingDemand(boolean declined) {
		this.declined = declined;
	}

	public ShippingDemand(PackagerInstance packagerInstance, Integer id, Date creationDate, Date lastUpdate,
			boolean declined, Set<ProductInstance> productInstances) {
		this.packagerInstance = packagerInstance;
		this.id = id;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.declined = declined;
		this.productInstances = productInstances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pack_id", unique = true, nullable = false)
	public Integer getPackId() {
		return this.packId;
	}

	public void setPackId(Integer packId) {
		this.packId = packId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_packager_instance")
	public PackagerInstance getPackagerInstance() {
		return this.packagerInstance;
	}

	public void setPackagerInstance(PackagerInstance packagerInstance) {
		this.packagerInstance = packagerInstance;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "declined", nullable = false)
	public boolean isDeclined() {
		return this.declined;
	}

	public void setDeclined(boolean declined) {
		this.declined = declined;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "shippingDemands")
	public Set<ProductInstance> getProductInstances() {
		return this.productInstances;
	}

	public void setProductInstances(Set<ProductInstance> productInstances) {
		this.productInstances = productInstances;
	}

	public ShippingDemand clone() {
		ShippingDemand dd = new ShippingDemand();

		dd.setCreationDate(this.getCreationDate());
		dd.setDeclined(this.isDeclined());
		dd.setPackagerInstance(this.getPackagerInstance());
		dd.setPackId(null);
		dd.setId(null);

		return dd;
	}
}
