package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VPackagerInfoProductLicenseKey generated by hbm2java
 */
@Entity
@Table(name = "v_packager_info_product_license_key", catalog = "nn_packager_management_recette_new")
public class VPackagerInfoProductLicenseKey implements java.io.Serializable {

	private VPackagerInfoProductLicenseKeyId id;

	public VPackagerInfoProductLicenseKey() {
	}

	public VPackagerInfoProductLicenseKey(VPackagerInfoProductLicenseKeyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "retailerPackagerId", column = @Column(name = "retailer_packager_id", nullable = false)),
			@AttributeOverride(name = "providerProductId", column = @Column(name = "provider_product_id", nullable = false)),
			@AttributeOverride(name = "licenseKey", column = @Column(name = "license_key")) })
	public VPackagerInfoProductLicenseKeyId getId() {
		return this.id;
	}

	public void setId(VPackagerInfoProductLicenseKeyId id) {
		this.id = id;
	}

}
