package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VPackager generated by hbm2java
 */
@Entity
@Table(name = "v_packager", catalog = "nn_packager_management_recette")
public class VPackager implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VPackagerId id;

	public VPackager() {
	}

	public VPackager(VPackagerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "packagerCreationDate", column = @Column(name = "packager_creation_date", nullable = false, length = 19)),
			@AttributeOverride(name = "retailerPackagerId", column = @Column(name = "retailer_packager_id", nullable = false)),
			@AttributeOverride(name = "packagerRetailerKey", column = @Column(name = "packager_retailer_key")),
			@AttributeOverride(name = "productCreationDate", column = @Column(name = "product_creation_date", nullable = false, length = 19)),
			@AttributeOverride(name = "providerProductId", column = @Column(name = "provider_product_id", nullable = false)),
			@AttributeOverride(name = "productRetailerKey", column = @Column(name = "product_retailer_key")),
			@AttributeOverride(name = "productLastKnownState", column = @Column(name = "product_last_known_state")) })
	public VPackagerId getId() {
		return this.id;
	}

	public void setId(VPackagerId id) {
		this.id = id;
	}

}
