package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPackprodId generated by hbm2java
 */
@Embeddable
public class VPackprodId implements java.io.Serializable {

	private Date packagerCreationDate;
	private String retailerPackagerId;
	private String model;
	private int idProductInstance;
	private String productModel;
	private String providerProductId;
	private String lastKnownState;
	private Date productCreationDate;

	public VPackprodId() {
	}

	public VPackprodId(Date packagerCreationDate, String retailerPackagerId, int idProductInstance,
			String providerProductId, Date productCreationDate) {
		this.packagerCreationDate = packagerCreationDate;
		this.retailerPackagerId = retailerPackagerId;
		this.idProductInstance = idProductInstance;
		this.providerProductId = providerProductId;
		this.productCreationDate = productCreationDate;
	}

	public VPackprodId(Date packagerCreationDate, String retailerPackagerId, String model, int idProductInstance,
			String productModel, String providerProductId, String lastKnownState, Date productCreationDate) {
		this.packagerCreationDate = packagerCreationDate;
		this.retailerPackagerId = retailerPackagerId;
		this.model = model;
		this.idProductInstance = idProductInstance;
		this.productModel = productModel;
		this.providerProductId = providerProductId;
		this.lastKnownState = lastKnownState;
		this.productCreationDate = productCreationDate;
	}

	@Column(name = "packager_creation_date", nullable = false, length = 19)
	public Date getPackagerCreationDate() {
		return this.packagerCreationDate;
	}

	public void setPackagerCreationDate(Date packagerCreationDate) {
		this.packagerCreationDate = packagerCreationDate;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "model")
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "id_product_instance", nullable = false)
	public int getIdProductInstance() {
		return this.idProductInstance;
	}

	public void setIdProductInstance(int idProductInstance) {
		this.idProductInstance = idProductInstance;
	}

	@Column(name = "product_model")
	public String getProductModel() {
		return this.productModel;
	}

	public void setProductModel(String productModel) {
		this.productModel = productModel;
	}

	@Column(name = "provider_product_id", nullable = false)
	public String getProviderProductId() {
		return this.providerProductId;
	}

	public void setProviderProductId(String providerProductId) {
		this.providerProductId = providerProductId;
	}

	@Column(name = "last_known_state")
	public String getLastKnownState() {
		return this.lastKnownState;
	}

	public void setLastKnownState(String lastKnownState) {
		this.lastKnownState = lastKnownState;
	}

	@Column(name = "product_creation_date", nullable = false, length = 19)
	public Date getProductCreationDate() {
		return this.productCreationDate;
	}

	public void setProductCreationDate(Date productCreationDate) {
		this.productCreationDate = productCreationDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPackprodId))
			return false;
		VPackprodId castOther = (VPackprodId) other;

		return ((this.getPackagerCreationDate() == castOther.getPackagerCreationDate())
				|| (this.getPackagerCreationDate() != null && castOther.getPackagerCreationDate() != null
						&& this.getPackagerCreationDate().equals(castOther.getPackagerCreationDate())))
				&& ((this.getRetailerPackagerId() == castOther.getRetailerPackagerId())
						|| (this.getRetailerPackagerId() != null && castOther.getRetailerPackagerId() != null
								&& this.getRetailerPackagerId().equals(castOther.getRetailerPackagerId())))
				&& ((this.getModel() == castOther.getModel()) || (this.getModel() != null
						&& castOther.getModel() != null && this.getModel().equals(castOther.getModel())))
				&& (this.getIdProductInstance() == castOther.getIdProductInstance())
				&& ((this.getProductModel() == castOther.getProductModel())
						|| (this.getProductModel() != null && castOther.getProductModel() != null
								&& this.getProductModel().equals(castOther.getProductModel())))
				&& ((this.getProviderProductId() == castOther.getProviderProductId())
						|| (this.getProviderProductId() != null && castOther.getProviderProductId() != null
								&& this.getProviderProductId().equals(castOther.getProviderProductId())))
				&& ((this.getLastKnownState() == castOther.getLastKnownState())
						|| (this.getLastKnownState() != null && castOther.getLastKnownState() != null
								&& this.getLastKnownState().equals(castOther.getLastKnownState())))
				&& ((this.getProductCreationDate() == castOther.getProductCreationDate())
						|| (this.getProductCreationDate() != null && castOther.getProductCreationDate() != null
								&& this.getProductCreationDate().equals(castOther.getProductCreationDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPackagerCreationDate() == null ? 0 : this.getPackagerCreationDate().hashCode());
		result = 37 * result + (getRetailerPackagerId() == null ? 0 : this.getRetailerPackagerId().hashCode());
		result = 37 * result + (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result + this.getIdProductInstance();
		result = 37 * result + (getProductModel() == null ? 0 : this.getProductModel().hashCode());
		result = 37 * result + (getProviderProductId() == null ? 0 : this.getProviderProductId().hashCode());
		result = 37 * result + (getLastKnownState() == null ? 0 : this.getLastKnownState().hashCode());
		result = 37 * result + (getProductCreationDate() == null ? 0 : this.getProductCreationDate().hashCode());
		return result;
	}

}
