package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPackagerId generated by hbm2java
 */
@Embeddable
public class VPackagerId implements java.io.Serializable {

	private Date packagerCreationDate;
	private String retailerPackagerId;
	private String packagerRetailerKey;
	private Date productCreationDate;
	private String providerProductId;
	private String productRetailerKey;
	private String productLastKnownState;

	public VPackagerId() {
	}

	public VPackagerId(Date packagerCreationDate, String retailerPackagerId, Date productCreationDate,
			String providerProductId) {
		this.packagerCreationDate = packagerCreationDate;
		this.retailerPackagerId = retailerPackagerId;
		this.productCreationDate = productCreationDate;
		this.providerProductId = providerProductId;
	}

	public VPackagerId(Date packagerCreationDate, String retailerPackagerId, String packagerRetailerKey,
			Date productCreationDate, String providerProductId, String productRetailerKey,
			String productLastKnownState) {
		this.packagerCreationDate = packagerCreationDate;
		this.retailerPackagerId = retailerPackagerId;
		this.packagerRetailerKey = packagerRetailerKey;
		this.productCreationDate = productCreationDate;
		this.providerProductId = providerProductId;
		this.productRetailerKey = productRetailerKey;
		this.productLastKnownState = productLastKnownState;
	}

	@Column(name = "packager_creation_date", nullable = false, length = 19)
	public Date getPackagerCreationDate() {
		return this.packagerCreationDate;
	}

	public void setPackagerCreationDate(Date packagerCreationDate) {
		this.packagerCreationDate = packagerCreationDate;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "packager_retailer_key")
	public String getPackagerRetailerKey() {
		return this.packagerRetailerKey;
	}

	public void setPackagerRetailerKey(String packagerRetailerKey) {
		this.packagerRetailerKey = packagerRetailerKey;
	}

	@Column(name = "product_creation_date", nullable = false, length = 19)
	public Date getProductCreationDate() {
		return this.productCreationDate;
	}

	public void setProductCreationDate(Date productCreationDate) {
		this.productCreationDate = productCreationDate;
	}

	@Column(name = "provider_product_id", nullable = false)
	public String getProviderProductId() {
		return this.providerProductId;
	}

	public void setProviderProductId(String providerProductId) {
		this.providerProductId = providerProductId;
	}

	@Column(name = "product_retailer_key")
	public String getProductRetailerKey() {
		return this.productRetailerKey;
	}

	public void setProductRetailerKey(String productRetailerKey) {
		this.productRetailerKey = productRetailerKey;
	}

	@Column(name = "product_last_known_state")
	public String getProductLastKnownState() {
		return this.productLastKnownState;
	}

	public void setProductLastKnownState(String productLastKnownState) {
		this.productLastKnownState = productLastKnownState;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPackagerId))
			return false;
		VPackagerId castOther = (VPackagerId) other;

		return ((this.getPackagerCreationDate() == castOther.getPackagerCreationDate())
				|| (this.getPackagerCreationDate() != null && castOther.getPackagerCreationDate() != null
						&& this.getPackagerCreationDate().equals(castOther.getPackagerCreationDate())))
				&& ((this.getRetailerPackagerId() == castOther.getRetailerPackagerId())
						|| (this.getRetailerPackagerId() != null && castOther.getRetailerPackagerId() != null
								&& this.getRetailerPackagerId().equals(castOther.getRetailerPackagerId())))
				&& ((this.getPackagerRetailerKey() == castOther.getPackagerRetailerKey())
						|| (this.getPackagerRetailerKey() != null && castOther.getPackagerRetailerKey() != null
								&& this.getPackagerRetailerKey().equals(castOther.getPackagerRetailerKey())))
				&& ((this.getProductCreationDate() == castOther.getProductCreationDate())
						|| (this.getProductCreationDate() != null && castOther.getProductCreationDate() != null
								&& this.getProductCreationDate().equals(castOther.getProductCreationDate())))
				&& ((this.getProviderProductId() == castOther.getProviderProductId())
						|| (this.getProviderProductId() != null && castOther.getProviderProductId() != null
								&& this.getProviderProductId().equals(castOther.getProviderProductId())))
				&& ((this.getProductRetailerKey() == castOther.getProductRetailerKey())
						|| (this.getProductRetailerKey() != null && castOther.getProductRetailerKey() != null
								&& this.getProductRetailerKey().equals(castOther.getProductRetailerKey())))
				&& ((this.getProductLastKnownState() == castOther.getProductLastKnownState())
						|| (this.getProductLastKnownState() != null && castOther.getProductLastKnownState() != null
								&& this.getProductLastKnownState().equals(castOther.getProductLastKnownState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPackagerCreationDate() == null ? 0 : this.getPackagerCreationDate().hashCode());
		result = 37 * result + (getRetailerPackagerId() == null ? 0 : this.getRetailerPackagerId().hashCode());
		result = 37 * result + (getPackagerRetailerKey() == null ? 0 : this.getPackagerRetailerKey().hashCode());
		result = 37 * result + (getProductCreationDate() == null ? 0 : this.getProductCreationDate().hashCode());
		result = 37 * result + (getProviderProductId() == null ? 0 : this.getProviderProductId().hashCode());
		result = 37 * result + (getProductRetailerKey() == null ? 0 : this.getProductRetailerKey().hashCode());
		result = 37 * result + (getProductLastKnownState() == null ? 0 : this.getProductLastKnownState().hashCode());
		return result;
	}

}
