package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPackagerAdminftId generated by hbm2java
 */
@Embeddable
public class VPackagerAdminftId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String retailerPackagerId;
	private String providerProductId;
	private String discriminatorValue;

	public VPackagerAdminftId() {
	}

	public VPackagerAdminftId(String retailerPackagerId, String providerProductId, String discriminatorValue) {
		this.retailerPackagerId = retailerPackagerId;
		this.providerProductId = providerProductId;
		this.discriminatorValue = discriminatorValue;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "provider_product_id", nullable = false)
	public String getProviderProductId() {
		return this.providerProductId;
	}

	public void setProviderProductId(String providerProductId) {
		this.providerProductId = providerProductId;
	}

	@Column(name = "discriminator_value", nullable = false)
	public String getDiscriminatorValue() {
		return this.discriminatorValue;
	}

	public void setDiscriminatorValue(String discriminatorValue) {
		this.discriminatorValue = discriminatorValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPackagerAdminftId))
			return false;
		VPackagerAdminftId castOther = (VPackagerAdminftId) other;

		return ((this.getRetailerPackagerId() == castOther.getRetailerPackagerId())
				|| (this.getRetailerPackagerId() != null && castOther.getRetailerPackagerId() != null
						&& this.getRetailerPackagerId().equals(castOther.getRetailerPackagerId())))
				&& ((this.getProviderProductId() == castOther.getProviderProductId())
						|| (this.getProviderProductId() != null && castOther.getProviderProductId() != null
								&& this.getProviderProductId().equals(castOther.getProviderProductId())))
				&& ((this.getDiscriminatorValue() == castOther.getDiscriminatorValue())
						|| (this.getDiscriminatorValue() != null && castOther.getDiscriminatorValue() != null
								&& this.getDiscriminatorValue().equals(castOther.getDiscriminatorValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRetailerPackagerId() == null ? 0 : this.getRetailerPackagerId().hashCode());
		result = 37 * result + (getProviderProductId() == null ? 0 : this.getProviderProductId().hashCode());
		result = 37 * result + (getDiscriminatorValue() == null ? 0 : this.getDiscriminatorValue().hashCode());
		return result;
	}

}
