package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPackagerInfoProductLicenseKeyId generated by hbm2java
 */
@Embeddable
public class VPackagerInfoProductLicenseKeyId implements java.io.Serializable {

	private String retailerPackagerId;
	private String providerProductId;
	private String licenseKey;

	public VPackagerInfoProductLicenseKeyId() {
	}

	public VPackagerInfoProductLicenseKeyId(String retailerPackagerId, String providerProductId) {
		this.retailerPackagerId = retailerPackagerId;
		this.providerProductId = providerProductId;
	}

	public VPackagerInfoProductLicenseKeyId(String retailerPackagerId, String providerProductId, String licenseKey) {
		this.retailerPackagerId = retailerPackagerId;
		this.providerProductId = providerProductId;
		this.licenseKey = licenseKey;
	}

	@Column(name = "retailer_packager_id", nullable = false)
	public String getRetailerPackagerId() {
		return this.retailerPackagerId;
	}

	public void setRetailerPackagerId(String retailerPackagerId) {
		this.retailerPackagerId = retailerPackagerId;
	}

	@Column(name = "provider_product_id", nullable = false)
	public String getProviderProductId() {
		return this.providerProductId;
	}

	public void setProviderProductId(String providerProductId) {
		this.providerProductId = providerProductId;
	}

	@Column(name = "license_key")
	public String getLicenseKey() {
		return this.licenseKey;
	}

	public void setLicenseKey(String licenseKey) {
		this.licenseKey = licenseKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPackagerInfoProductLicenseKeyId))
			return false;
		VPackagerInfoProductLicenseKeyId castOther = (VPackagerInfoProductLicenseKeyId) other;

		return ((this.getRetailerPackagerId() == castOther.getRetailerPackagerId())
				|| (this.getRetailerPackagerId() != null && castOther.getRetailerPackagerId() != null
						&& this.getRetailerPackagerId().equals(castOther.getRetailerPackagerId())))
				&& ((this.getProviderProductId() == castOther.getProviderProductId())
						|| (this.getProviderProductId() != null && castOther.getProviderProductId() != null
								&& this.getProviderProductId().equals(castOther.getProviderProductId())))
				&& ((this.getLicenseKey() == castOther.getLicenseKey())
						|| (this.getLicenseKey() != null && castOther.getLicenseKey() != null
								&& this.getLicenseKey().equals(castOther.getLicenseKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRetailerPackagerId() == null ? 0 : this.getRetailerPackagerId().hashCode());
		result = 37 * result + (getProviderProductId() == null ? 0 : this.getProviderProductId().hashCode());
		result = 37 * result + (getLicenseKey() == null ? 0 : this.getLicenseKey().hashCode());
		return result;
	}

}
