package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VsDatabaseDiagrams generated by hbm2java
 */
@Entity
@Table(name = "vs_database_diagrams", catalog = "nn_packager_management_recette")
public class VsDatabaseDiagrams implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VsDatabaseDiagramsId id;

	public VsDatabaseDiagrams() {
	}

	public VsDatabaseDiagrams(VsDatabaseDiagramsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", length = 80)),
			@AttributeOverride(name = "diadata", column = @Column(name = "diadata", length = 65535)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 1022)),
			@AttributeOverride(name = "preview", column = @Column(name = "preview", length = 65535)),
			@AttributeOverride(name = "lockinfo", column = @Column(name = "lockinfo", length = 80)),
			@AttributeOverride(name = "locktime", column = @Column(name = "locktime", nullable = false, length = 19)),
			@AttributeOverride(name = "version", column = @Column(name = "version", length = 80)) })
	public VsDatabaseDiagramsId getId() {
		return this.id;
	}

	public void setId(VsDatabaseDiagramsId id) {
		this.id = id;
	}

}
