package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VsDatabaseDiagramsId generated by hbm2java
 */
@Embeddable
public class VsDatabaseDiagramsId implements java.io.Serializable {

	private String name;
	private String diadata;
	private String comment;
	private String preview;
	private String lockinfo;
	private Date locktime;
	private String version;

	public VsDatabaseDiagramsId() {
	}

	public VsDatabaseDiagramsId(Date locktime) {
		this.locktime = locktime;
	}

	public VsDatabaseDiagramsId(String name, String diadata, String comment, String preview, String lockinfo,
			Date locktime, String version) {
		this.name = name;
		this.diadata = diadata;
		this.comment = comment;
		this.preview = preview;
		this.lockinfo = lockinfo;
		this.locktime = locktime;
		this.version = version;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "diadata", length = 65535)
	public String getDiadata() {
		return this.diadata;
	}

	public void setDiadata(String diadata) {
		this.diadata = diadata;
	}

	@Column(name = "comment", length = 1022)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "preview", length = 65535)
	public String getPreview() {
		return this.preview;
	}

	public void setPreview(String preview) {
		this.preview = preview;
	}

	@Column(name = "lockinfo", length = 80)
	public String getLockinfo() {
		return this.lockinfo;
	}

	public void setLockinfo(String lockinfo) {
		this.lockinfo = lockinfo;
	}

	@Column(name = "locktime", nullable = false, length = 19)
	public Date getLocktime() {
		return this.locktime;
	}

	public void setLocktime(Date locktime) {
		this.locktime = locktime;
	}

	@Column(name = "version", length = 80)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VsDatabaseDiagramsId))
			return false;
		VsDatabaseDiagramsId castOther = (VsDatabaseDiagramsId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getDiadata() == castOther.getDiadata()) || (this.getDiadata() != null
						&& castOther.getDiadata() != null && this.getDiadata().equals(castOther.getDiadata())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())))
				&& ((this.getPreview() == castOther.getPreview()) || (this.getPreview() != null
						&& castOther.getPreview() != null && this.getPreview().equals(castOther.getPreview())))
				&& ((this.getLockinfo() == castOther.getLockinfo()) || (this.getLockinfo() != null
						&& castOther.getLockinfo() != null && this.getLockinfo().equals(castOther.getLockinfo())))
				&& ((this.getLocktime() == castOther.getLocktime()) || (this.getLocktime() != null
						&& castOther.getLocktime() != null && this.getLocktime().equals(castOther.getLocktime())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDiadata() == null ? 0 : this.getDiadata().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result + (getPreview() == null ? 0 : this.getPreview().hashCode());
		result = 37 * result + (getLockinfo() == null ? 0 : this.getLockinfo().hashCode());
		result = 37 * result + (getLocktime() == null ? 0 : this.getLocktime().hashCode());
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		return result;
	}

}
