package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VTransformation generated by hbm2java
 */
@Entity
@Table(name = "v_transformation", catalog = "nn_packager_management_recette")
public class VTransformation implements java.io.Serializable {

	private VTransformationId id;

	public VTransformation() {
	}

	public VTransformation(VTransformationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productActionId", column = @Column(name = "product_action_id", nullable = false)),
			@AttributeOverride(name = "packagerActionId", column = @Column(name = "packager_action_id", nullable = false)),
			@AttributeOverride(name = "srcProductModel", column = @Column(name = "src_product_model")),
			@AttributeOverride(name = "destProductModel", column = @Column(name = "dest_product_model")),
			@AttributeOverride(name = "productAction", column = @Column(name = "product_action")),
			@AttributeOverride(name = "transformationDate", column = @Column(name = "transformation_date", length = 19)),
			@AttributeOverride(name = "srcPackagerModel", column = @Column(name = "src_packager_model")),
			@AttributeOverride(name = "destPackagerModel", column = @Column(name = "dest_packager_model")),
			@AttributeOverride(name = "srcRetailerPackagerId", column = @Column(name = "src_retailer_packager_id")),
			@AttributeOverride(name = "destRetailerPackagerId", column = @Column(name = "dest_retailer_packager_id")) })
	public VTransformationId getId() {
		return this.id;
	}

	public void setId(VTransformationId id) {
		this.id = id;
	}

}
