package tn.wevioo.entities;
// Generated 28 mars 2017 22:31:56 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VTransformationId generated by hbm2java
 */
@Embeddable
public class VTransformationId implements java.io.Serializable {

	private int productActionId;
	private int packagerActionId;
	private String srcProductModel;
	private String destProductModel;
	private String productAction;
	private Date transformationDate;
	private String srcPackagerModel;
	private String destPackagerModel;
	private String srcRetailerPackagerId;
	private String destRetailerPackagerId;

	public VTransformationId() {
	}

	public VTransformationId(int productActionId, int packagerActionId) {
		this.productActionId = productActionId;
		this.packagerActionId = packagerActionId;
	}

	public VTransformationId(int productActionId, int packagerActionId, String srcProductModel, String destProductModel,
			String productAction, Date transformationDate, String srcPackagerModel, String destPackagerModel,
			String srcRetailerPackagerId, String destRetailerPackagerId) {
		this.productActionId = productActionId;
		this.packagerActionId = packagerActionId;
		this.srcProductModel = srcProductModel;
		this.destProductModel = destProductModel;
		this.productAction = productAction;
		this.transformationDate = transformationDate;
		this.srcPackagerModel = srcPackagerModel;
		this.destPackagerModel = destPackagerModel;
		this.srcRetailerPackagerId = srcRetailerPackagerId;
		this.destRetailerPackagerId = destRetailerPackagerId;
	}

	@Column(name = "product_action_id", nullable = false)
	public int getProductActionId() {
		return this.productActionId;
	}

	public void setProductActionId(int productActionId) {
		this.productActionId = productActionId;
	}

	@Column(name = "packager_action_id", nullable = false)
	public int getPackagerActionId() {
		return this.packagerActionId;
	}

	public void setPackagerActionId(int packagerActionId) {
		this.packagerActionId = packagerActionId;
	}

	@Column(name = "src_product_model")
	public String getSrcProductModel() {
		return this.srcProductModel;
	}

	public void setSrcProductModel(String srcProductModel) {
		this.srcProductModel = srcProductModel;
	}

	@Column(name = "dest_product_model")
	public String getDestProductModel() {
		return this.destProductModel;
	}

	public void setDestProductModel(String destProductModel) {
		this.destProductModel = destProductModel;
	}

	@Column(name = "product_action")
	public String getProductAction() {
		return this.productAction;
	}

	public void setProductAction(String productAction) {
		this.productAction = productAction;
	}

	@Column(name = "transformation_date", length = 19)
	public Date getTransformationDate() {
		return this.transformationDate;
	}

	public void setTransformationDate(Date transformationDate) {
		this.transformationDate = transformationDate;
	}

	@Column(name = "src_packager_model")
	public String getSrcPackagerModel() {
		return this.srcPackagerModel;
	}

	public void setSrcPackagerModel(String srcPackagerModel) {
		this.srcPackagerModel = srcPackagerModel;
	}

	@Column(name = "dest_packager_model")
	public String getDestPackagerModel() {
		return this.destPackagerModel;
	}

	public void setDestPackagerModel(String destPackagerModel) {
		this.destPackagerModel = destPackagerModel;
	}

	@Column(name = "src_retailer_packager_id")
	public String getSrcRetailerPackagerId() {
		return this.srcRetailerPackagerId;
	}

	public void setSrcRetailerPackagerId(String srcRetailerPackagerId) {
		this.srcRetailerPackagerId = srcRetailerPackagerId;
	}

	@Column(name = "dest_retailer_packager_id")
	public String getDestRetailerPackagerId() {
		return this.destRetailerPackagerId;
	}

	public void setDestRetailerPackagerId(String destRetailerPackagerId) {
		this.destRetailerPackagerId = destRetailerPackagerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTransformationId))
			return false;
		VTransformationId castOther = (VTransformationId) other;

		return (this.getProductActionId() == castOther.getProductActionId())
				&& (this.getPackagerActionId() == castOther.getPackagerActionId())
				&& ((this.getSrcProductModel() == castOther.getSrcProductModel())
						|| (this.getSrcProductModel() != null && castOther.getSrcProductModel() != null
								&& this.getSrcProductModel().equals(castOther.getSrcProductModel())))
				&& ((this.getDestProductModel() == castOther.getDestProductModel())
						|| (this.getDestProductModel() != null && castOther.getDestProductModel() != null
								&& this.getDestProductModel().equals(castOther.getDestProductModel())))
				&& ((this.getProductAction() == castOther.getProductAction())
						|| (this.getProductAction() != null && castOther.getProductAction() != null
								&& this.getProductAction().equals(castOther.getProductAction())))
				&& ((this.getTransformationDate() == castOther.getTransformationDate())
						|| (this.getTransformationDate() != null && castOther.getTransformationDate() != null
								&& this.getTransformationDate().equals(castOther.getTransformationDate())))
				&& ((this.getSrcPackagerModel() == castOther.getSrcPackagerModel())
						|| (this.getSrcPackagerModel() != null && castOther.getSrcPackagerModel() != null
								&& this.getSrcPackagerModel().equals(castOther.getSrcPackagerModel())))
				&& ((this.getDestPackagerModel() == castOther.getDestPackagerModel())
						|| (this.getDestPackagerModel() != null && castOther.getDestPackagerModel() != null
								&& this.getDestPackagerModel().equals(castOther.getDestPackagerModel())))
				&& ((this.getSrcRetailerPackagerId() == castOther.getSrcRetailerPackagerId())
						|| (this.getSrcRetailerPackagerId() != null && castOther.getSrcRetailerPackagerId() != null
								&& this.getSrcRetailerPackagerId().equals(castOther.getSrcRetailerPackagerId())))
				&& ((this.getDestRetailerPackagerId() == castOther.getDestRetailerPackagerId())
						|| (this.getDestRetailerPackagerId() != null && castOther.getDestRetailerPackagerId() != null
								&& this.getDestRetailerPackagerId().equals(castOther.getDestRetailerPackagerId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductActionId();
		result = 37 * result + this.getPackagerActionId();
		result = 37 * result + (getSrcProductModel() == null ? 0 : this.getSrcProductModel().hashCode());
		result = 37 * result + (getDestProductModel() == null ? 0 : this.getDestProductModel().hashCode());
		result = 37 * result + (getProductAction() == null ? 0 : this.getProductAction().hashCode());
		result = 37 * result + (getTransformationDate() == null ? 0 : this.getTransformationDate().hashCode());
		result = 37 * result + (getSrcPackagerModel() == null ? 0 : this.getSrcPackagerModel().hashCode());
		result = 37 * result + (getDestPackagerModel() == null ? 0 : this.getDestPackagerModel().hashCode());
		result = 37 * result + (getSrcRetailerPackagerId() == null ? 0 : this.getSrcRetailerPackagerId().hashCode());
		result = 37 * result + (getDestRetailerPackagerId() == null ? 0 : this.getDestRetailerPackagerId().hashCode());
		return result;
	}

}
