spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nn_packager_management_recette?zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver    
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS : false    
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
server:
  port: 8092
  
