//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.29 at 10:24:47 AM EEST 
//


package tn.wevioo.model.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendDelivery",
    "receiver",
    "properties",
    "customerId",
    "complementaryDirective"
})
@XmlRootElement(name = "deliveryRequest")
public class DeliveryRequest {

    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected boolean sendDelivery;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected ReceiverContact receiver;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected List<DeliveryProperty> properties;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String customerId;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String complementaryDirective;

    public boolean isSendDelivery() {
        return sendDelivery;
    }
    
    public void setSendDelivery(boolean value) {
        this.sendDelivery = value;
    }

    public ReceiverContact getReceiver() {
        return receiver;
    }

    public void setReceiver(ReceiverContact value) {
        this.receiver = value;
    }

    public List<DeliveryProperty> getProperties() {
        if (properties == null) {
            properties = new ArrayList<DeliveryProperty>();
        }
        return this.properties;
    }
    
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String value) {
        this.customerId = value;
    }

    public String getComplementaryDirective() {
        return complementaryDirective;
    }

    public void setComplementaryDirective(String value) {
        this.complementaryDirective = value;
    }

}
