//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.29 at 10:24:47 AM EEST 
//


package tn.wevioo.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceiverContact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiverContact", propOrder = {

})
public class ReceiverContact {

    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String firstName;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String lastName;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String company;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String email;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String phoneNumber;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected DeliveryAddress address;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected ReceiverCivility civility;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String value) {
        this.firstName = value;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String value) {
        this.lastName = value;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String value) {
        this.company = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    public DeliveryAddress getAddress() {
        return address;
    }

    public void setAddress(DeliveryAddress value) {
        this.address = value;
    }

    public ReceiverCivility getCivility() {
        return civility;
    }

    public void setCivility(ReceiverCivility value) {
        this.civility = value;
    }

}
