//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.29 at 10:24:47 AM EEST 
//


package tn.wevioo.packager.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryAddress", propOrder = {

})
public class DeliveryAddress {

    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String address1;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String address2;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String address3;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String zipCode;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String country;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager", required = true)
    protected String city;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String cedexCode;
    @XmlElement(namespace = "http://www.nordnet.com/nordnet/Packager")
    protected String cedexLabel;

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String value) {
        this.address1 = value;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String value) {
        this.address2 = value;
    }

    public String getAddress3() {
        return address3;
    }

    public void setAddress3(String value) {
        this.address3 = value;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String value) {
        this.zipCode = value;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String value) {
        this.country = value;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String value) {
        this.city = value;
    }

    public String getCedexCode() {
        return cedexCode;
    }

    public void setCedexCode(String value) {
        this.cedexCode = value;
    }

    public String getCedexLabel() {
        return cedexLabel;
    }

    public void setCedexLabel(String value) {
        this.cedexLabel = value;
    }

}
