//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.29 at 10:24:47 AM EEST 
//


package tn.wevioo.packager.model.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

@XmlEnum
public enum ReceiverCivility {

    @XmlEnumValue("M.")
    M("M."),
    @XmlEnumValue("Mlle")
    MLLE("Mlle"),
    @XmlEnumValue("Mme")
    MME("Mme");
    private final String value;

    ReceiverCivility(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReceiverCivility fromValue(String v) {
        for (ReceiverCivility c: ReceiverCivility.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
